/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { KYCVerification__factory } from "./KYCVerification__factory";
export { UserCellRegistry__factory } from "./UserCellRegistry__factory";
