import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from "next/link";

import styles from 'tauri/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
    
        <div className={styles.center}>
         
          <div className={styles.thirteen}>
            <Image
              src="/logo.png"
              alt="Fin Wallet"
              width={350}
              height={231}
              priority
            />
          </div>
        </div>
        <Link
            href="/home"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Get Started <span>-&gt;</span>
            </h2>
  
          </Link>

      
      </main>
    </>
  )
}
